### ISSUE TITLE
Can I still plot just a subset of variables?

### ISSUE THREAD

**Issue by goedman** [TuringLang/MCMCChain.jl#22]
A MWE is below script (the README example) where I am trying to just plot param2 from chn1:

```
using MCMCChain
using StatPlots

ProjDir = dirname(@__FILE__)
cd(ProjDir)

theme(:ggplot2);

# Define the experiment
n_iter = 10;
n_name = 3;
n_chain = 2;

# experiment results
val = randn(n_iter, n_name, n_chain) .+ [1, 2, 3]';
val = hcat(val, rand(1:2, n_iter, 1, n_chain));

# construct a Chains object
chn = Chains(val);

chn1 = chn[1:size(chn, 1), 2, 1:size(chn, 3)]

# visualize the MCMC simulation results
p1 = plot(chn1)
p2 = plot(chn1, colordim = :parameter)

# save to a png file
savefig(p1, "demo-plot-parameters.png")
savefig(p2, "demo-plot-chains.png")
```

This used (maybe a month ago?) to work. But I know you've also been updating the plotting.

Thanks,
Rob

**Comment by trappmartin** [comment]
This is a very strange bug. 
```
plot(chn1)
```
seems to work fine but 
```
plot(chn1, colordim = :parameter)
```
doesn't work anymore.

**Comment by goedman** [comment]
Yes, deep in Plots or Recipes it tries to access with an index 1+noofvars in the subset Chains object while it works fine with the original (not subsetted) Chains object.

**Comment by goedman** [comment]
A workaround is to generate a new Chains object from a subset of the original data, i.e. with

```
chn1 = Chains(val[:, 2,  :]);
p4 = plot(chn1, color dim = :parameter)
```

works fine.

**Comment by goedman** [comment]
Tricky stuff. Above example is not correct as `size(val[:, 2, :])` will return (n_iter, n_chain). This way chn1 is created with a single chain. But val[:, 2, 1:n_chain] works.

Unfortunately, neither approach works for Stan/CmdStan draw arrays.
